#!/usr/bin/env python3
"""Generates vocabulary.ts from a data file."""

words = [
    # (id, french, english, pos, category, sentenceFR, sentenceEN)
    (1,"bonjour","hello, good morning","interjection","greetings","Bonjour, comment allez-vous ?","Hello, how are you?"),
    (2,"merci","thank you","interjection","greetings","Merci beaucoup pour votre aide.","Thank you very much for your help."),
    (3,"s'il vous plaît","please (formal)","expression","courtesy","Puis-je avoir un café, s'il vous plaît ?","Can I have a coffee, please?"),
    (4,"au revoir","goodbye","interjection","greetings","Au revoir et à bientôt !","Goodbye and see you soon!"),
    (5,"oui","yes","adverb","basics","Oui, je comprends très bien.","Yes, I understand very well."),
    (6,"non","no","adverb","basics","Non, merci. Je n'ai pas faim.","No, thank you. I'm not hungry."),
    (7,"salut","hi, bye (informal)","interjection","greetings","Salut, ça va ?","Hi, how's it going?"),
    (8,"pardon","excuse me, sorry","interjection","courtesy","Pardon, où est la gare ?","Excuse me, where is the train station?"),
    (9,"être","to be","verb","verbs","Je suis étudiant en France.","I am a student in France."),
    (10,"avoir","to have","verb","verbs","J'ai deux sœurs et un frère.","I have two sisters and a brother."),
    (11,"faire","to do, to make","verb","verbs","Je fais mes devoirs chaque soir.","I do my homework every evening."),
    (12,"pouvoir","to be able to, can","verb","verbs","Est-ce que je peux vous aider ?","Can I help you?"),
    (13,"vouloir","to want","verb","verbs","Je veux apprendre le français.","I want to learn French."),
    (14,"savoir","to know (facts)","verb","verbs","Je sais où est la bibliothèque.","I know where the library is."),
    (15,"aller","to go","verb","verbs","Nous allons au marché demain.","We are going to the market tomorrow."),
    (16,"venir","to come","verb","verbs","Il vient de Paris ce matin.","He is coming from Paris this morning."),
    (17,"manger","to eat","verb","food","Nous mangeons au restaurant ce soir.","We are eating at the restaurant tonight."),
    (18,"boire","to drink","verb","food","Je bois du café chaque matin.","I drink coffee every morning."),
    (19,"parler","to speak, to talk","verb","verbs","Je parle français un peu.","I speak French a little."),
    (20,"voir","to see","verb","verbs","Je vois la tour Eiffel de ma fenêtre.","I see the Eiffel Tower from my window."),
    (21,"vouloir","to want","verb","verbs","Nous voulons voyager en France.","We want to travel to France."),
    (22,"prendre","to take, to have (drink)","verb","verbs","Je prends le petit-déjeuner à sept heures.","I have breakfast at seven o'clock."),
    (23,"croire","to believe, to think","verb","verbs","Je crois que c'est une bonne idée.","I think that's a good idea."),
    (24,"devenir","to become","verb","verbs","Il veut devenir médecin.","He wants to become a doctor."),
    (25,"devoir","must, to have to","verb","verbs","Je dois partir maintenant.","I must leave now."),
    (26,"dire","to say, to tell","verb","verbs","Dis-moi la vérité.","Tell me the truth."),
    (27,"mettre","to put, to place","verb","verbs","Je mets mes clés sur la table.","I put my keys on the table."),
    (28,"lire","to read","verb","verbs","Elle lit un roman intéressant.","She is reading an interesting novel."),
    (29,"écrire","to write","verb","verbs","J'écris une lettre à mon ami.","I am writing a letter to my friend."),
    (30,"comprendre","to understand","verb","verbs","Je ne comprends pas cette phrase.","I don't understand this sentence."),
    (31,"appeler","to call","verb","verbs","Appelle-moi quand tu arrives.","Call me when you arrive."),
    (32,"chercher","to look for","verb","verbs","Je cherche mon téléphone.","I am looking for my phone."),
    (33,"trouver","to find","verb","verbs","J'ai trouvé un bon restaurant.","I found a good restaurant."),
    (34,"donner","to give","verb","verbs","Il donne un cadeau à sa mère.","He gives a gift to his mother."),
    (35,"montrer","to show","verb","verbs","Montre-moi tes photos de voyage.","Show me your travel photos."),
    (36,"expliquer","to explain","verb","verbs","Le professeur explique la grammaire.","The teacher explains the grammar."),
    (37,"finir","to finish","verb","verbs","Je finis mon travail à cinq heures.","I finish my work at five o'clock."),
    (38,"changer","to change","verb","verbs","Il faut changer de train ici.","You have to change trains here."),
    (39,"oublier","to forget","verb","verbs","N'oublie pas ton parapluie.","Don't forget your umbrella."),
    (40,"se souvenir","to remember","verb","verbs","Je me souviens de notre voyage.","I remember our trip."),
    (41,"apprendre","to learn","verb","verbs","J'apprends le français depuis deux ans.","I have been learning French for two years."),
    (42,"enseigner","to teach","verb","verbs","Elle enseigne l'histoire au lycée.","She teaches history at high school."),
    (43,"répondre","to answer, to reply","verb","verbs","Personne n'a répondu à ma question.","Nobody answered my question."),
    (44,"poser","to put, to ask (question)","verb","verbs","Je pose une question au professeur.","I ask the teacher a question."),
    (45,"offrir","to offer, to give (gift)","verb","verbs","Il offre des fleurs à sa femme.","He gives flowers to his wife."),
    (46,"connaitre","to know (person/place)","verb","verbs","Je connais bien Paris.","I know Paris well."),
    (47,"repondre","to answer","verb","verbs","Répondez à la question, s'il vous plaît.","Answer the question, please."),
    (48,"partir","to leave, to depart","verb","verbs","Le train part à midi.","The train leaves at noon."),
    (49,"arriver","to arrive","verb","verbs","Le vol arrive à l'heure.","The flight arrives on time."),
    (50,"rester","to stay, to remain","verb","verbs","Je reste à la maison ce week-end.","I am staying home this weekend."),
    (51,"homme","man","noun","m","people","L'homme parle au téléphone.","The man is talking on the phone."),
    (52,"femme","woman","noun","f","people","La femme porte une robe bleue.","The woman is wearing a blue dress."),
    (53,"enfant","child","noun","m/f","people","Les enfants jouent dans le jardin.","The children are playing in the garden."),
    (54,"ami","friend","noun","m","relationships","C'est un vieil ami de mon père.","He is an old friend of my father."),
    (55,"maison","house, home","noun","f","places","Notre maison a trois chambres.","Our house has three bedrooms."),
    (56,"travail","work, job","noun","m","work","J'aime beaucoup mon travail.","I really like my job."),
    (57,"temps","time, weather","noun","m","time","Je n'ai pas beaucoup de temps.","I don't have much time."),
    (58,"ville","city, town","noun","f","places","Paris est une belle ville.","Paris is a beautiful city."),
    (59,"pays","country","noun","m","places","La France est un beau pays.","France is a beautiful country."),
    (60,"jour","day","noun","m","time","Je pars dans trois jours.","I am leaving in three days."),
    (61,"semaine","week","noun","f","time","Nous voyageons la semaine prochaine.","We are traveling next week."),
    (62,"mois","month","noun","m","time","Il a neigé plusieurs fois ce mois.","It snowed several times this month."),
    (63,"année","year","noun","f","time","Bonne année !","Happy New Year!"),
    (64,"matin","morning","noun","m","time","Je me lève à sept heures du matin.","I wake up at seven in the morning."),
    (65,"soir","evening","noun","m","time","Nous dînons ensemble chaque soir.","We have dinner together every evening."),
    (66,"nuit","night","noun","f","time","Je dors très bien la nuit.","I sleep very well at night."),
    (67,"eau","water","noun","f","food","Un verre d'eau, s'il vous plaît.","A glass of water, please."),
    (68,"pain","bread","noun","m","food","Je comprais du pain ce matin.","I bought bread this morning."),
    (69,"lait","milk","noun","m","food","Les enfants boivent du lait le matin.","The children drink milk in the morning."),
    (70,"vin","wine","noun","m","food","Le vin français est très célèbre.","French wine is very famous."),
    (71,"café","coffee","noun","m","food","Je prends un café après le déjeuner.","I have a coffee after lunch."),
    (72,"thé","tea","noun","m","food","Préférez-vous le thé ou le café ?","Do you prefer tea or coffee?"),
    (73,"riz","rice","noun","m","food","Le riz est un aliment de base.","Rice is a staple food."),
    (74,"viande","meat","noun","f","food","Je ne mange pas de viande.","I don't eat meat."),
    (75,"poisson","fish","noun","m","food","Nous avons mangé du poisson hier soir.","We ate fish last night."),
    (76,"légume","vegetable","noun","m","food","Mange tes légumes !","Eat your vegetables!"),
    (77,"fruit","fruit","noun","m","food","Les fruits frais sont meilleurs.","Fresh fruits are better."),
    (78,"restaurant","restaurant","noun","m","food","Le restaurant était complet.","The restaurant was fully booked."),
    (79,"hôtel","hotel","noun","m","travel","Nous avons réservé un hôtel.","We have booked a hotel."),
    (80,"gare","train station","noun","f","travel","La gare est à deux kilomètres.","The train station is two kilometers away."),
    (81,"aéroport","airport","noun","m","travel","L'avion a atterri à l'aéroport.","The plane landed at the airport."),
    (82,"rue","street","noun","f","places","La rue est très animée le soir.","The street is very lively in the evening."),
    (83,"pont","bridge","noun","m","places","Le pont enjambe la Seine.","The bridge spans the Seine."),
    (84,"bureau","office, desk","noun","m","work","Je travaille dans un grand bureau.","I work in a big office."),
    (85,"école","school","noun","f","education","Les enfants vont à l'école à pied.","The children walk to school."),
    (86,"livre","book","noun","m","culture","J'ai lu ce livre l'année dernière.","I read this book last year."),
    (87,"film","film, movie","noun","m","culture","Quel film voulez-vous voir ?","Which film do you want to watch?"),
    (88,"musique","music","noun","f","culture","J'écoute de la musique classique.","I listen to classical music."),
    (89,"temps","time","noun","m","time","Le temps passe si vite.","Time flies so fast."),
    (90,"premier","first","adjective","m","numbers","C'est mon premier voyage en France.","It's my first trip to France."),
    (91,"deuxième","second","adjective","m/f","numbers","Il habite au deuxième étage.","He lives on the second floor."),
    (92,"dernier","last","adjective","m","basics","C'est le dernier jour de vacation.","It's the last day of vacation."),
    (93,"grand","big, tall, great","adjective","m","description","Paris est une très grande ville.","Paris is a very big city."),
    (94,"petit","small, short","adjective","m","description","J'habite dans un petit appartement.","I live in a small apartment."),
    (95,"nouveau","new","adjective","m","description","C'est un nouveau restaurant français.","It's a new French restaurant."),
    (96,"bon","good","adjective","m","description","Ce vin est très bon.","This wine is very good."),
    (97,"mauvais","bad","adjective","m","description","Le temps est mauvais aujourd'hui.","The weather is bad today."),
    (98,"jeune","young","adjective","m/f","description","C'est une jeune artiste talentueuse.","She is a talented young artist."),
    (99,"vieux","old","adjective","m","description","Mon vieux ordinateur ne marche plus.","My old computer doesn't work anymore."),
    (100,"beau","beautiful","adjective","m","description","Il fait beau aujourd'hui.","The weather is beautiful today."),
]

lines = ["export interface VocabWord {", "  id: number;", '  french: string;', '  english: string;', '  partOfSpeech: string;', '  category: string;', '  sentenceFR: string;', '  sentenceEN: string;', "  audioUrl?: string;", "}", "", "export const vocabulary: VocabWord[] = ["]
for w in words:
    lines.append(f'  {{ id:{w[0]}, french:"{w[1]}", english:"{w[2]}", partOfSpeech:"{w[3]}", category:"{w[4]}", sentenceFR:"{w[5]}", sentenceEN:"{w[6]}" }},')
lines.append("];")
with open("D:/Development/WORK/french-learn-app/src/data/vocabulary.ts", "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
print(f"Written {len(words)} words to vocabulary.ts")
